### ISSUE TITLE
[Feature Request] Find SCCM Server

### ISSUE THREAD

**Issue by florianib** [shelltrail/cmloot#2]
Would it be possible to add a featuer like in [SCCMHunter](https://github.com/shelltrail/cmloot) which tries to enumerate SCCM servers?

Reason for that would be to streamline the usage of the tool.

The search can be done with LDAP by looking for the value `objectClass=mSSMSManagementPoint`.

Would be cool if we could query all SCCM servers and download all files automatically

Thanks!

**Comment by vikerup** [comment]
Hello,

Sorry for the late reply. It's been busy the last couple weeks.
I'll definitively look in to this!

Thanks for the idea

**Comment by florianib** [comment]
Thank you!

You can also check out my pull request where I added support for downloading from multiple sccm servers!

**Comment by vikerup** [comment]
Implemented. Feel free to test it out
